/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { PhonkArenaResults } from "./PhonkArenaResults";
export * as factories from "./factories";
export { PhonkArenaResults__factory } from "./factories/PhonkArenaResults__factory";
