/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export interface PhonkArenaResultsInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "finalizeMatch"
      | "finalized"
      | "minDuration"
      | "startMatch"
      | "startTimes"
      | "started"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic: "MatchFinalized" | "MatchStarted"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "finalizeMatch",
    values: [BytesLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "finalized",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "minDuration",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "startMatch",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "startTimes",
    values: [BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "started", values: [BytesLike]): string;

  decodeFunctionResult(
    functionFragment: "finalizeMatch",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "finalized", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "minDuration",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "startMatch", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "startTimes", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "started", data: BytesLike): Result;
}

export namespace MatchFinalizedEvent {
  export type InputTuple = [
    matchId: BytesLike,
    winner: BigNumberish,
    endTime: BigNumberish
  ];
  export type OutputTuple = [matchId: string, winner: bigint, endTime: bigint];
  export interface OutputObject {
    matchId: string;
    winner: bigint;
    endTime: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace MatchStartedEvent {
  export type InputTuple = [matchId: BytesLike, startTime: BigNumberish];
  export type OutputTuple = [matchId: string, startTime: bigint];
  export interface OutputObject {
    matchId: string;
    startTime: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface PhonkArenaResults extends BaseContract {
  connect(runner?: ContractRunner | null): PhonkArenaResults;
  waitForDeployment(): Promise<this>;

  interface: PhonkArenaResultsInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  finalizeMatch: TypedContractMethod<
    [matchId: BytesLike, winner: BigNumberish],
    [void],
    "nonpayable"
  >;

  finalized: TypedContractMethod<[arg0: BytesLike], [boolean], "view">;

  minDuration: TypedContractMethod<[], [bigint], "view">;

  startMatch: TypedContractMethod<[matchId: BytesLike], [void], "nonpayable">;

  startTimes: TypedContractMethod<[arg0: BytesLike], [bigint], "view">;

  started: TypedContractMethod<[arg0: BytesLike], [boolean], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "finalizeMatch"
  ): TypedContractMethod<
    [matchId: BytesLike, winner: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "finalized"
  ): TypedContractMethod<[arg0: BytesLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "minDuration"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "startMatch"
  ): TypedContractMethod<[matchId: BytesLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "startTimes"
  ): TypedContractMethod<[arg0: BytesLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "started"
  ): TypedContractMethod<[arg0: BytesLike], [boolean], "view">;

  getEvent(
    key: "MatchFinalized"
  ): TypedContractEvent<
    MatchFinalizedEvent.InputTuple,
    MatchFinalizedEvent.OutputTuple,
    MatchFinalizedEvent.OutputObject
  >;
  getEvent(
    key: "MatchStarted"
  ): TypedContractEvent<
    MatchStartedEvent.InputTuple,
    MatchStartedEvent.OutputTuple,
    MatchStartedEvent.OutputObject
  >;

  filters: {
    "MatchFinalized(bytes32,uint8,uint256)": TypedContractEvent<
      MatchFinalizedEvent.InputTuple,
      MatchFinalizedEvent.OutputTuple,
      MatchFinalizedEvent.OutputObject
    >;
    MatchFinalized: TypedContractEvent<
      MatchFinalizedEvent.InputTuple,
      MatchFinalizedEvent.OutputTuple,
      MatchFinalizedEvent.OutputObject
    >;

    "MatchStarted(bytes32,uint256)": TypedContractEvent<
      MatchStartedEvent.InputTuple,
      MatchStartedEvent.OutputTuple,
      MatchStartedEvent.OutputObject
    >;
    MatchStarted: TypedContractEvent<
      MatchStartedEvent.InputTuple,
      MatchStartedEvent.OutputTuple,
      MatchStartedEvent.OutputObject
    >;
  };
}
